version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis_cache
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - redis_cache
      - rabbitmq
    networks:
      - queueless_net

  redis_cache:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - queueless_net

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - queueless_net

volumes:
  redis_data:

networks:
  queueless_net:
    driver: bridge
