sonar.projectKey=neutron420_Lineo
sonar.organization=neutron420
sonar.host.url=https://sonarcloud.io

# Source paths
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/vendor/**,**/*.test.go,**/*.spec.ts,lineo-fe/.next/**

# Language specific configs
sonar.go.gosec.reportPaths=gosec-report.json
sonar.javascript.lcov.reportPaths=lineo-fe/coverage/lcov.info
